/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 110
#define LARGE_STATE_COUNT 35
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 2
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_SEMI = 3,
  anon_sym_BSLASH_DOT = 4,
  sym_symbol = 5,
  anon_sym_DOT = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_COLON = 13,
  anon_sym_DQUOTE = 14,
  aux_sym_string_token1 = 15,
  sym_string_escape = 16,
  sym_number = 17,
  sym_long_string = 18,
  sym_long_string_escape = 19,
  sym_source_file = 20,
  sym_comment = 21,
  sym__form = 22,
  sym__form_not_dot = 23,
  sym__lambda_content = 24,
  sym_lambda = 25,
  sym_block = 26,
  sym_data = 27,
  sym_call = 28,
  sym_pair = 29,
  sym_string = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym__lambda_content_repeat1 = 32,
  aux_sym_string_repeat1 = 33,
  alias_sym_body = 34,
  alias_sym_parameters = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SEMI] = ";",
  [anon_sym_BSLASH_DOT] = "symbol",
  [sym_symbol] = "symbol",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_string_escape] = "string_escape",
  [sym_number] = "number",
  [sym_long_string] = "long_string",
  [sym_long_string_escape] = "long_string_escape",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym__form] = "_form",
  [sym__form_not_dot] = "_form_not_dot",
  [sym__lambda_content] = "_lambda_content",
  [sym_lambda] = "lambda",
  [sym_block] = "block",
  [sym_data] = "data",
  [sym_call] = "call",
  [sym_pair] = "pair",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__lambda_content_repeat1] = "_lambda_content_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_body] = "body",
  [alias_sym_parameters] = "parameters",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_BSLASH_DOT] = sym_symbol,
  [sym_symbol] = sym_symbol,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_string_escape] = sym_string_escape,
  [sym_number] = sym_number,
  [sym_long_string] = sym_long_string,
  [sym_long_string_escape] = sym_long_string_escape,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym__form] = sym__form,
  [sym__form_not_dot] = sym__form_not_dot,
  [sym__lambda_content] = sym__lambda_content,
  [sym_lambda] = sym_lambda,
  [sym_block] = sym_block,
  [sym_data] = sym_data,
  [sym_call] = sym_call,
  [sym_pair] = sym_pair,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__lambda_content_repeat1] = aux_sym__lambda_content_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_body] = alias_sym_body,
  [alias_sym_parameters] = alias_sym_parameters,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DOT] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_long_string] = {
    .visible = true,
    .named = true,
  },
  [sym_long_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym__form_not_dot] = {
    .visible = false,
    .named = true,
  },
  [sym__lambda_content] = {
    .visible = false,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_data] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__lambda_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_body] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_parameters] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_body,
  },
  [2] = {
    [0] = alias_sym_parameters,
  },
  [3] = {
    [0] = alias_sym_parameters,
    [2] = alias_sym_body,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__lambda_content_repeat1, 3,
    aux_sym__lambda_content_repeat1,
    alias_sym_body,
    alias_sym_parameters,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 2,
  [7] = 2,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 12,
  [13] = 9,
  [14] = 9,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 17,
  [20] = 15,
  [21] = 21,
  [22] = 16,
  [23] = 21,
  [24] = 18,
  [25] = 17,
  [26] = 26,
  [27] = 16,
  [28] = 21,
  [29] = 18,
  [30] = 17,
  [31] = 31,
  [32] = 16,
  [33] = 21,
  [34] = 18,
  [35] = 35,
  [36] = 36,
  [37] = 35,
  [38] = 35,
  [39] = 36,
  [40] = 35,
  [41] = 36,
  [42] = 36,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 54,
  [58] = 58,
  [59] = 48,
  [60] = 46,
  [61] = 47,
  [62] = 49,
  [63] = 44,
  [64] = 50,
  [65] = 51,
  [66] = 52,
  [67] = 53,
  [68] = 55,
  [69] = 51,
  [70] = 55,
  [71] = 54,
  [72] = 47,
  [73] = 48,
  [74] = 50,
  [75] = 52,
  [76] = 49,
  [77] = 58,
  [78] = 46,
  [79] = 53,
  [80] = 44,
  [81] = 81,
  [82] = 82,
  [83] = 82,
  [84] = 82,
  [85] = 81,
  [86] = 81,
  [87] = 82,
  [88] = 88,
  [89] = 81,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 93,
  [96] = 93,
  [97] = 93,
  [98] = 44,
  [99] = 55,
  [100] = 54,
  [101] = 101,
  [102] = 51,
  [103] = 103,
  [104] = 48,
  [105] = 49,
  [106] = 50,
  [107] = 47,
  [108] = 52,
  [109] = 53,
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '\''}, {'*', '9'}, {'<', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        '"', 85,
        '(', 82,
        ')', 83,
        '.', 77,
        ':', 84,
        ';', 70,
        '[', 80,
        '\\', 32,
        ']', 81,
        '{', 78,
        '}', 79,
        '+', 73,
        '-', 73,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ';') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(29);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(12);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 85,
        '(', 82,
        '.', 77,
        ':', 84,
        ';', 70,
        '[', 80,
        '\\', 33,
        '{', 78,
        '}', 79,
        '+', 73,
        '-', 73,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(76);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(85);
      if (lookahead == ';') ADVANCE(70);
      if (lookahead == '\\') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == '.') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'a') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 9:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'a') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'a') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'c') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'd') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 15:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'g') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'g') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 19:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'k') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'n') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'p') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(14);
      if (lookahead == 's') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 26:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 't') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'u') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 28:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == 'v') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == '(') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 30:
      if (lookahead == '(') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 31:
      if (lookahead == '(') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ADVANCE_MAP(
        '.', 71,
        '\\', 76,
        '0', 88,
        '<', 88,
        '>', 88,
        'a', 88,
        'b', 88,
        'n', 88,
        'r', 88,
        't', 88,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ':' ||
          lookahead == ';' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(76);
      END_STATE();
    case 33:
      if (lookahead == '.') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ':' ||
          lookahead == ';' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(76);
      END_STATE();
    case 34:
      ADVANCE_MAP(
        '0', 88,
        '<', 88,
        '>', 88,
        '\\', 88,
        'a', 88,
        'b', 88,
        'n', 88,
        'r', 88,
        't', 88,
      );
      END_STATE();
    case 35:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ':' ||
          lookahead == ';' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(76);
      END_STATE();
    case 36:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        '"', 85,
        '(', 82,
        ')', 83,
        ':', 84,
        ';', 70,
        '[', 80,
        '\\', 35,
        ']', 81,
        '{', 78,
        '+', 73,
        '-', 73,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(76);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == ' ') ADVANCE(65);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == ')') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == ')') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == '.') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'a') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'c') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'd') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'g') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'g') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'k') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'l') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(50);
      if (lookahead == 's') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'r') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 't') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'u') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead == 'v') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ';') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead == ';') ADVANCE(68);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_BSLASH_DOT);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      if ((!eof && set_contains(sym_symbol_character_set_1, 10, lookahead))) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '\\') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if ((!eof && set_contains(sym_symbol_character_set_1, 10, lookahead))) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '\\') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      if ((!eof && set_contains(sym_symbol_character_set_1, 10, lookahead))) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '\\') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      if ((!eof && set_contains(sym_symbol_character_set_1, 10, lookahead))) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '\\') ADVANCE(35);
      if ((!eof && set_contains(sym_symbol_character_set_1, 10, lookahead))) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ';') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(86);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_string_escape);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'e') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 36},
  [16] = {.lex_state = 36},
  [17] = {.lex_state = 36},
  [18] = {.lex_state = 36},
  [19] = {.lex_state = 36},
  [20] = {.lex_state = 36},
  [21] = {.lex_state = 36},
  [22] = {.lex_state = 36},
  [23] = {.lex_state = 36},
  [24] = {.lex_state = 36},
  [25] = {.lex_state = 36},
  [26] = {.lex_state = 36},
  [27] = {.lex_state = 36},
  [28] = {.lex_state = 36},
  [29] = {.lex_state = 36},
  [30] = {.lex_state = 36},
  [31] = {.lex_state = 36},
  [32] = {.lex_state = 36},
  [33] = {.lex_state = 36},
  [34] = {.lex_state = 36},
  [35] = {.lex_state = 36},
  [36] = {.lex_state = 36},
  [37] = {.lex_state = 36},
  [38] = {.lex_state = 36},
  [39] = {.lex_state = 36},
  [40] = {.lex_state = 36},
  [41] = {.lex_state = 36},
  [42] = {.lex_state = 36},
  [43] = {.lex_state = 36},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 4},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 36},
  [58] = {.lex_state = 36},
  [59] = {.lex_state = 36},
  [60] = {.lex_state = 36},
  [61] = {.lex_state = 36},
  [62] = {.lex_state = 36},
  [63] = {.lex_state = 36},
  [64] = {.lex_state = 36},
  [65] = {.lex_state = 36},
  [66] = {.lex_state = 36},
  [67] = {.lex_state = 36},
  [68] = {.lex_state = 36},
  [69] = {.lex_state = 36},
  [70] = {.lex_state = 36},
  [71] = {.lex_state = 36},
  [72] = {.lex_state = 36},
  [73] = {.lex_state = 36},
  [74] = {.lex_state = 36},
  [75] = {.lex_state = 36},
  [76] = {.lex_state = 36},
  [77] = {.lex_state = 36},
  [78] = {.lex_state = 36},
  [79] = {.lex_state = 36},
  [80] = {.lex_state = 36},
  [81] = {.lex_state = 5},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 5},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {(TSStateId)(-1),},
  [99] = {(TSStateId)(-1),},
  [100] = {(TSStateId)(-1),},
  [101] = {(TSStateId)(-1),},
  [102] = {(TSStateId)(-1),},
  [103] = {(TSStateId)(-1),},
  [104] = {(TSStateId)(-1),},
  [105] = {(TSStateId)(-1),},
  [106] = {(TSStateId)(-1),},
  [107] = {(TSStateId)(-1),},
  [108] = {(TSStateId)(-1),},
  [109] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_string_escape] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_long_string] = ACTIONS(1),
    [sym_long_string_escape] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(92),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_token1] = ACTIONS(7),
    [aux_sym_comment_token1] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_comment] = STATE(2),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym__lambda_content] = STATE(97),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(9),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(3)] = {
    [sym_comment] = STATE(3),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym__lambda_content] = STATE(94),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(8),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(4)] = {
    [sym_comment] = STATE(4),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym__lambda_content] = STATE(91),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(10),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(5)] = {
    [sym_comment] = STATE(5),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym__lambda_content] = STATE(93),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(6)] = {
    [sym_comment] = STATE(6),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym__lambda_content] = STATE(95),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(13),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(7)] = {
    [sym_comment] = STATE(7),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym__lambda_content] = STATE(96),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(14),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(8)] = {
    [sym_comment] = STATE(8),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(12),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(9)] = {
    [sym_comment] = STATE(9),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(12),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(10)] = {
    [sym_comment] = STATE(10),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(12),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(11)] = {
    [sym_comment] = STATE(11),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(12),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(12)] = {
    [sym_comment] = STATE(12),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(12),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(51),
    [sym_symbol] = ACTIONS(54),
    [anon_sym_DOT] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(62),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_COLON] = ACTIONS(68),
    [anon_sym_DQUOTE] = ACTIONS(71),
    [sym_number] = ACTIONS(74),
  },
  [STATE(13)] = {
    [sym_comment] = STATE(13),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(12),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(14)] = {
    [sym_comment] = STATE(14),
    [sym__form] = STATE(45),
    [sym__form_not_dot] = STATE(56),
    [sym_lambda] = STATE(46),
    [sym_block] = STATE(46),
    [sym_data] = STATE(46),
    [sym_call] = STATE(46),
    [sym_pair] = STATE(46),
    [sym_string] = STATE(46),
    [aux_sym__lambda_content_repeat1] = STATE(12),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_BSLASH_DOT] = ACTIONS(11),
    [sym_symbol] = ACTIONS(13),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(79),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(15)] = {
    [sym_comment] = STATE(15),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(84),
    [anon_sym_LBRACK] = ACTIONS(87),
    [anon_sym_RBRACK] = ACTIONS(90),
    [anon_sym_LPAREN] = ACTIONS(92),
    [anon_sym_RPAREN] = ACTIONS(90),
    [anon_sym_COLON] = ACTIONS(95),
    [anon_sym_DQUOTE] = ACTIONS(98),
    [sym_number] = ACTIONS(101),
  },
  [STATE(16)] = {
    [sym_comment] = STATE(16),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(18),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(110),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(17)] = {
    [sym_comment] = STATE(17),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(120),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(18)] = {
    [sym_comment] = STATE(18),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(122),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(19)] = {
    [sym_comment] = STATE(19),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(124),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(20)] = {
    [sym_comment] = STATE(20),
    [sym__form] = STATE(77),
    [sym_lambda] = STATE(78),
    [sym_block] = STATE(78),
    [sym_data] = STATE(78),
    [sym_call] = STATE(78),
    [sym_pair] = STATE(78),
    [sym_string] = STATE(78),
    [aux_sym_source_file_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(90),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(126),
    [anon_sym_LBRACE] = ACTIONS(129),
    [anon_sym_LBRACK] = ACTIONS(132),
    [anon_sym_LPAREN] = ACTIONS(135),
    [anon_sym_COLON] = ACTIONS(138),
    [anon_sym_DQUOTE] = ACTIONS(141),
    [sym_number] = ACTIONS(144),
  },
  [STATE(21)] = {
    [sym_comment] = STATE(21),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(19),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(147),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(22)] = {
    [sym_comment] = STATE(22),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(24),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(149),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(23)] = {
    [sym_comment] = STATE(23),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(25),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(151),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(24)] = {
    [sym_comment] = STATE(24),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(153),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(25)] = {
    [sym_comment] = STATE(25),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(155),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(26)] = {
    [sym_comment] = STATE(26),
    [sym__form] = STATE(77),
    [sym_lambda] = STATE(78),
    [sym_block] = STATE(78),
    [sym_data] = STATE(78),
    [sym_call] = STATE(78),
    [sym_pair] = STATE(78),
    [sym_string] = STATE(78),
    [aux_sym_source_file_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(157),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(159),
    [anon_sym_LBRACE] = ACTIONS(161),
    [anon_sym_LBRACK] = ACTIONS(163),
    [anon_sym_LPAREN] = ACTIONS(165),
    [anon_sym_COLON] = ACTIONS(167),
    [anon_sym_DQUOTE] = ACTIONS(169),
    [sym_number] = ACTIONS(171),
  },
  [STATE(27)] = {
    [sym_comment] = STATE(27),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(29),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(173),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(28)] = {
    [sym_comment] = STATE(28),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(30),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(175),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(29)] = {
    [sym_comment] = STATE(29),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(177),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(30)] = {
    [sym_comment] = STATE(30),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(179),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(31)] = {
    [sym_comment] = STATE(31),
    [sym__form] = STATE(77),
    [sym_lambda] = STATE(78),
    [sym_block] = STATE(78),
    [sym_data] = STATE(78),
    [sym_call] = STATE(78),
    [sym_pair] = STATE(78),
    [sym_string] = STATE(78),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(181),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(159),
    [anon_sym_LBRACE] = ACTIONS(161),
    [anon_sym_LBRACK] = ACTIONS(163),
    [anon_sym_LPAREN] = ACTIONS(165),
    [anon_sym_COLON] = ACTIONS(167),
    [anon_sym_DQUOTE] = ACTIONS(169),
    [sym_number] = ACTIONS(171),
  },
  [STATE(32)] = {
    [sym_comment] = STATE(32),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(34),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(183),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(33)] = {
    [sym_comment] = STATE(33),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(17),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_RPAREN] = ACTIONS(185),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
  [STATE(34)] = {
    [sym_comment] = STATE(34),
    [sym__form] = STATE(58),
    [sym_lambda] = STATE(60),
    [sym_block] = STATE(60),
    [sym_data] = STATE(60),
    [sym_call] = STATE(60),
    [sym_pair] = STATE(60),
    [sym_string] = STATE(60),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym_symbol] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(108),
    [anon_sym_RBRACK] = ACTIONS(187),
    [anon_sym_LPAREN] = ACTIONS(112),
    [anon_sym_COLON] = ACTIONS(114),
    [anon_sym_DQUOTE] = ACTIONS(116),
    [sym_number] = ACTIONS(118),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(189), 1,
      sym_symbol,
    ACTIONS(191), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 1,
      anon_sym_LBRACK,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(197), 1,
      anon_sym_COLON,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    ACTIONS(201), 1,
      sym_number,
    STATE(35), 1,
      sym_comment,
    STATE(100), 7,
      sym__form,
      sym_lambda,
      sym_block,
      sym_data,
      sym_call,
      sym_pair,
      sym_string,
  [40] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(104), 1,
      sym_symbol,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 1,
      anon_sym_COLON,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(35), 1,
      sym__form,
    STATE(36), 1,
      sym_comment,
    STATE(60), 6,
      sym_lambda,
      sym_block,
      sym_data,
      sym_call,
      sym_pair,
      sym_string,
  [82] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(159), 1,
      sym_symbol,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 1,
      anon_sym_LBRACK,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    ACTIONS(167), 1,
      anon_sym_COLON,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
    ACTIONS(171), 1,
      sym_number,
    STATE(37), 1,
      sym_comment,
    STATE(71), 1,
      sym__form,
    STATE(78), 6,
      sym_lambda,
      sym_block,
      sym_data,
      sym_call,
      sym_pair,
      sym_string,
  [124] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(13), 1,
      sym_symbol,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_COLON,
    ACTIONS(27), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_number,
    STATE(38), 1,
      sym_comment,
    STATE(54), 1,
      sym__form,
    STATE(46), 6,
      sym_lambda,
      sym_block,
      sym_data,
      sym_call,
      sym_pair,
      sym_string,
  [166] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(104), 1,
      sym_symbol,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 1,
      anon_sym_COLON,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(39), 1,
      sym_comment,
    STATE(40), 1,
      sym__form,
    STATE(60), 6,
      sym_lambda,
      sym_block,
      sym_data,
      sym_call,
      sym_pair,
      sym_string,
  [208] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(104), 1,
      sym_symbol,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 1,
      anon_sym_COLON,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(40), 1,
      sym_comment,
    STATE(57), 1,
      sym__form,
    STATE(60), 6,
      sym_lambda,
      sym_block,
      sym_data,
      sym_call,
      sym_pair,
      sym_string,
  [250] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(104), 1,
      sym_symbol,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 1,
      anon_sym_COLON,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(37), 1,
      sym__form,
    STATE(41), 1,
      sym_comment,
    STATE(60), 6,
      sym_lambda,
      sym_block,
      sym_data,
      sym_call,
      sym_pair,
      sym_string,
  [292] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(104), 1,
      sym_symbol,
    ACTIONS(106), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 1,
      anon_sym_COLON,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_number,
    STATE(38), 1,
      sym__form,
    STATE(42), 1,
      sym_comment,
    STATE(60), 6,
      sym_lambda,
      sym_block,
      sym_data,
      sym_call,
      sym_pair,
      sym_string,
  [334] = 11,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(191), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 1,
      anon_sym_LBRACK,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(197), 1,
      anon_sym_COLON,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    ACTIONS(203), 1,
      sym_symbol,
    ACTIONS(205), 1,
      sym_number,
    STATE(43), 1,
      sym_comment,
    STATE(101), 7,
      sym__form,
      sym_lambda,
      sym_block,
      sym_data,
      sym_call,
      sym_pair,
      sym_string,
  [374] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(209), 1,
      sym_symbol,
    STATE(44), 1,
      sym_comment,
    ACTIONS(207), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [398] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(213), 1,
      sym_symbol,
    STATE(45), 1,
      sym_comment,
    ACTIONS(211), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [422] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(217), 1,
      sym_symbol,
    STATE(46), 1,
      sym_comment,
    ACTIONS(215), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [446] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(221), 1,
      sym_symbol,
    STATE(47), 1,
      sym_comment,
    ACTIONS(219), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [470] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(225), 1,
      sym_symbol,
    STATE(48), 1,
      sym_comment,
    ACTIONS(223), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [494] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(229), 1,
      sym_symbol,
    STATE(49), 1,
      sym_comment,
    ACTIONS(227), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [518] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(233), 1,
      sym_symbol,
    STATE(50), 1,
      sym_comment,
    ACTIONS(231), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [542] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(237), 1,
      sym_symbol,
    STATE(51), 1,
      sym_comment,
    ACTIONS(235), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [566] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(241), 1,
      sym_symbol,
    STATE(52), 1,
      sym_comment,
    ACTIONS(239), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [590] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(245), 1,
      sym_symbol,
    STATE(53), 1,
      sym_comment,
    ACTIONS(243), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [614] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(249), 1,
      sym_symbol,
    STATE(54), 1,
      sym_comment,
    ACTIONS(247), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [638] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(253), 1,
      sym_symbol,
    STATE(55), 1,
      sym_comment,
    ACTIONS(251), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [662] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(257), 1,
      sym_symbol,
    STATE(56), 1,
      sym_comment,
    ACTIONS(255), 9,
      anon_sym_BSLASH_DOT,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [686] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(249), 1,
      sym_symbol,
    STATE(57), 1,
      sym_comment,
    ACTIONS(247), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [709] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(259), 1,
      sym_symbol,
    STATE(58), 1,
      sym_comment,
    ACTIONS(261), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [732] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(225), 1,
      sym_symbol,
    STATE(59), 1,
      sym_comment,
    ACTIONS(223), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [755] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(217), 1,
      sym_symbol,
    STATE(60), 1,
      sym_comment,
    ACTIONS(215), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [778] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(221), 1,
      sym_symbol,
    STATE(61), 1,
      sym_comment,
    ACTIONS(219), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [801] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(229), 1,
      sym_symbol,
    STATE(62), 1,
      sym_comment,
    ACTIONS(227), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [824] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(209), 1,
      sym_symbol,
    STATE(63), 1,
      sym_comment,
    ACTIONS(207), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [847] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(233), 1,
      sym_symbol,
    STATE(64), 1,
      sym_comment,
    ACTIONS(231), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [870] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(237), 1,
      sym_symbol,
    STATE(65), 1,
      sym_comment,
    ACTIONS(235), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [893] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(241), 1,
      sym_symbol,
    STATE(66), 1,
      sym_comment,
    ACTIONS(239), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [916] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(245), 1,
      sym_symbol,
    STATE(67), 1,
      sym_comment,
    ACTIONS(243), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [939] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(253), 1,
      sym_symbol,
    STATE(68), 1,
      sym_comment,
    ACTIONS(251), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [962] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(237), 1,
      sym_symbol,
    STATE(69), 1,
      sym_comment,
    ACTIONS(235), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [984] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(253), 1,
      sym_symbol,
    STATE(70), 1,
      sym_comment,
    ACTIONS(251), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1006] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(249), 1,
      sym_symbol,
    STATE(71), 1,
      sym_comment,
    ACTIONS(247), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1028] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(221), 1,
      sym_symbol,
    STATE(72), 1,
      sym_comment,
    ACTIONS(219), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1050] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(225), 1,
      sym_symbol,
    STATE(73), 1,
      sym_comment,
    ACTIONS(223), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1072] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(233), 1,
      sym_symbol,
    STATE(74), 1,
      sym_comment,
    ACTIONS(231), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1094] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(241), 1,
      sym_symbol,
    STATE(75), 1,
      sym_comment,
    ACTIONS(239), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1116] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(229), 1,
      sym_symbol,
    STATE(76), 1,
      sym_comment,
    ACTIONS(227), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1138] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(259), 1,
      sym_symbol,
    STATE(77), 1,
      sym_comment,
    ACTIONS(261), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1160] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(217), 1,
      sym_symbol,
    STATE(78), 1,
      sym_comment,
    ACTIONS(215), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1182] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(245), 1,
      sym_symbol,
    STATE(79), 1,
      sym_comment,
    ACTIONS(243), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1204] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(209), 1,
      sym_symbol,
    STATE(80), 1,
      sym_comment,
    ACTIONS(207), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [1226] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(263), 1,
      anon_sym_DQUOTE,
    STATE(81), 1,
      sym_comment,
    STATE(88), 1,
      aux_sym_string_repeat1,
    ACTIONS(265), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [1246] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(267), 1,
      anon_sym_DQUOTE,
    STATE(81), 1,
      aux_sym_string_repeat1,
    STATE(82), 1,
      sym_comment,
    ACTIONS(265), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [1266] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(269), 1,
      anon_sym_DQUOTE,
    STATE(83), 1,
      sym_comment,
    STATE(86), 1,
      aux_sym_string_repeat1,
    ACTIONS(265), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [1286] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(271), 1,
      anon_sym_DQUOTE,
    STATE(84), 1,
      sym_comment,
    STATE(85), 1,
      aux_sym_string_repeat1,
    ACTIONS(265), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [1306] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(273), 1,
      anon_sym_DQUOTE,
    STATE(85), 1,
      sym_comment,
    STATE(88), 1,
      aux_sym_string_repeat1,
    ACTIONS(265), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [1326] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(275), 1,
      anon_sym_DQUOTE,
    STATE(86), 1,
      sym_comment,
    STATE(88), 1,
      aux_sym_string_repeat1,
    ACTIONS(265), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [1346] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(277), 1,
      anon_sym_DQUOTE,
    STATE(87), 1,
      sym_comment,
    STATE(89), 1,
      aux_sym_string_repeat1,
    ACTIONS(265), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [1366] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(279), 1,
      anon_sym_DQUOTE,
    ACTIONS(281), 2,
      aux_sym_string_token1,
      sym_string_escape,
    STATE(88), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [1384] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(284), 1,
      anon_sym_DQUOTE,
    STATE(88), 1,
      aux_sym_string_repeat1,
    STATE(89), 1,
      sym_comment,
    ACTIONS(265), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [1404] = 4,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    STATE(90), 1,
      sym_comment,
    ACTIONS(286), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      sym_string_escape,
  [1419] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_comment,
  [1432] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(290), 1,
      ts_builtin_sym_end,
    STATE(92), 1,
      sym_comment,
  [1445] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      sym_comment,
  [1458] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(294), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      sym_comment,
  [1471] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      sym_comment,
  [1484] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(298), 1,
      anon_sym_RBRACE,
    STATE(96), 1,
      sym_comment,
  [1497] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(300), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      sym_comment,
  [1510] = 1,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
  [1514] = 1,
    ACTIONS(251), 1,
      ts_builtin_sym_end,
  [1518] = 1,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
  [1522] = 1,
    ACTIONS(302), 1,
      ts_builtin_sym_end,
  [1526] = 1,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [1530] = 1,
    ACTIONS(304), 1,
      ts_builtin_sym_end,
  [1534] = 1,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
  [1538] = 1,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
  [1542] = 1,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
  [1546] = 1,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
  [1550] = 1,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
  [1554] = 1,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(35)] = 0,
  [SMALL_STATE(36)] = 40,
  [SMALL_STATE(37)] = 82,
  [SMALL_STATE(38)] = 124,
  [SMALL_STATE(39)] = 166,
  [SMALL_STATE(40)] = 208,
  [SMALL_STATE(41)] = 250,
  [SMALL_STATE(42)] = 292,
  [SMALL_STATE(43)] = 334,
  [SMALL_STATE(44)] = 374,
  [SMALL_STATE(45)] = 398,
  [SMALL_STATE(46)] = 422,
  [SMALL_STATE(47)] = 446,
  [SMALL_STATE(48)] = 470,
  [SMALL_STATE(49)] = 494,
  [SMALL_STATE(50)] = 518,
  [SMALL_STATE(51)] = 542,
  [SMALL_STATE(52)] = 566,
  [SMALL_STATE(53)] = 590,
  [SMALL_STATE(54)] = 614,
  [SMALL_STATE(55)] = 638,
  [SMALL_STATE(56)] = 662,
  [SMALL_STATE(57)] = 686,
  [SMALL_STATE(58)] = 709,
  [SMALL_STATE(59)] = 732,
  [SMALL_STATE(60)] = 755,
  [SMALL_STATE(61)] = 778,
  [SMALL_STATE(62)] = 801,
  [SMALL_STATE(63)] = 824,
  [SMALL_STATE(64)] = 847,
  [SMALL_STATE(65)] = 870,
  [SMALL_STATE(66)] = 893,
  [SMALL_STATE(67)] = 916,
  [SMALL_STATE(68)] = 939,
  [SMALL_STATE(69)] = 962,
  [SMALL_STATE(70)] = 984,
  [SMALL_STATE(71)] = 1006,
  [SMALL_STATE(72)] = 1028,
  [SMALL_STATE(73)] = 1050,
  [SMALL_STATE(74)] = 1072,
  [SMALL_STATE(75)] = 1094,
  [SMALL_STATE(76)] = 1116,
  [SMALL_STATE(77)] = 1138,
  [SMALL_STATE(78)] = 1160,
  [SMALL_STATE(79)] = 1182,
  [SMALL_STATE(80)] = 1204,
  [SMALL_STATE(81)] = 1226,
  [SMALL_STATE(82)] = 1246,
  [SMALL_STATE(83)] = 1266,
  [SMALL_STATE(84)] = 1286,
  [SMALL_STATE(85)] = 1306,
  [SMALL_STATE(86)] = 1326,
  [SMALL_STATE(87)] = 1346,
  [SMALL_STATE(88)] = 1366,
  [SMALL_STATE(89)] = 1384,
  [SMALL_STATE(90)] = 1404,
  [SMALL_STATE(91)] = 1419,
  [SMALL_STATE(92)] = 1432,
  [SMALL_STATE(93)] = 1445,
  [SMALL_STATE(94)] = 1458,
  [SMALL_STATE(95)] = 1471,
  [SMALL_STATE(96)] = 1484,
  [SMALL_STATE(97)] = 1497,
  [SMALL_STATE(98)] = 1510,
  [SMALL_STATE(99)] = 1514,
  [SMALL_STATE(100)] = 1518,
  [SMALL_STATE(101)] = 1522,
  [SMALL_STATE(102)] = 1526,
  [SMALL_STATE(103)] = 1530,
  [SMALL_STATE(104)] = 1534,
  [SMALL_STATE(105)] = 1538,
  [SMALL_STATE(106)] = 1542,
  [SMALL_STATE(107)] = 1546,
  [SMALL_STATE(108)] = 1550,
  [SMALL_STATE(109)] = 1554,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 2, 0, 2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 2, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 3, 0, 3),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__form_not_dot, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__form_not_dot, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__form, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__form, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__lambda_content_repeat1, 1, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [281] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 3, 0, 2),
  [290] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 2, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_long_string = 0,
  ts_external_token_long_string_escape = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_long_string] = sym_long_string,
  [ts_external_token_long_string_escape] = sym_long_string_escape,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_long_string] = true,
    [ts_external_token_long_string_escape] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_aardvark_external_scanner_create(void);
void tree_sitter_aardvark_external_scanner_destroy(void *);
bool tree_sitter_aardvark_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_aardvark_external_scanner_serialize(void *, char *);
void tree_sitter_aardvark_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_aardvark(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_aardvark_external_scanner_create,
      tree_sitter_aardvark_external_scanner_destroy,
      tree_sitter_aardvark_external_scanner_scan,
      tree_sitter_aardvark_external_scanner_serialize,
      tree_sitter_aardvark_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "aardvark",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
