/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 94
#define LARGE_STATE_COUNT 36
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 2
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  aux_sym_comment_token1 = 2,
  anon_sym_SEMI = 3,
  sym__symbol_shared = 4,
  anon_sym_DOT = 5,
  anon_sym_BSLASH_DOT = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_COLON = 13,
  anon_sym_DQUOTE = 14,
  aux_sym_string_token1 = 15,
  sym_string_escape = 16,
  sym_number = 17,
  sym_long_string = 18,
  sym_long_string_escape = 19,
  sym_source_file = 20,
  sym_comment = 21,
  sym__form_shared = 22,
  sym__form = 23,
  sym__form_not_dot = 24,
  sym_symbol = 25,
  sym__symbol_not_dot = 26,
  sym__lambda_content = 27,
  sym_lambda = 28,
  sym_block = 29,
  sym_data = 30,
  sym_call = 31,
  sym_pair = 32,
  sym_string = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym__lambda_content_repeat1 = 35,
  aux_sym_string_repeat1 = 36,
  alias_sym_body = 37,
  alias_sym_parameters = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SEMI] = ";",
  [sym__symbol_shared] = "_symbol_shared",
  [anon_sym_DOT] = ".",
  [anon_sym_BSLASH_DOT] = "symbol",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_string_escape] = "string_escape",
  [sym_number] = "number",
  [sym_long_string] = "long_string",
  [sym_long_string_escape] = "long_string_escape",
  [sym_source_file] = "source_file",
  [sym_comment] = "comment",
  [sym__form_shared] = "_form_shared",
  [sym__form] = "_form",
  [sym__form_not_dot] = "_form_not_dot",
  [sym_symbol] = "symbol",
  [sym__symbol_not_dot] = "_symbol_not_dot",
  [sym__lambda_content] = "_lambda_content",
  [sym_lambda] = "lambda",
  [sym_block] = "block",
  [sym_data] = "data",
  [sym_call] = "call",
  [sym_pair] = "pair",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__lambda_content_repeat1] = "_lambda_content_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [alias_sym_body] = "body",
  [alias_sym_parameters] = "parameters",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym__symbol_shared] = sym__symbol_shared,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_BSLASH_DOT] = sym_symbol,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_string_escape] = sym_string_escape,
  [sym_number] = sym_number,
  [sym_long_string] = sym_long_string,
  [sym_long_string_escape] = sym_long_string_escape,
  [sym_source_file] = sym_source_file,
  [sym_comment] = sym_comment,
  [sym__form_shared] = sym__form_shared,
  [sym__form] = sym__form,
  [sym__form_not_dot] = sym__form_not_dot,
  [sym_symbol] = sym_symbol,
  [sym__symbol_not_dot] = sym__symbol_not_dot,
  [sym__lambda_content] = sym__lambda_content,
  [sym_lambda] = sym_lambda,
  [sym_block] = sym_block,
  [sym_data] = sym_data,
  [sym_call] = sym_call,
  [sym_pair] = sym_pair,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__lambda_content_repeat1] = aux_sym__lambda_content_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [alias_sym_body] = alias_sym_body,
  [alias_sym_parameters] = alias_sym_parameters,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym__symbol_shared] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DOT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_long_string] = {
    .visible = true,
    .named = true,
  },
  [sym_long_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__form_shared] = {
    .visible = false,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym__form_not_dot] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym__symbol_not_dot] = {
    .visible = false,
    .named = true,
  },
  [sym__lambda_content] = {
    .visible = false,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_data] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__lambda_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_body] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_parameters] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_symbol,
  },
  [2] = {
    [1] = alias_sym_body,
  },
  [3] = {
    [0] = alias_sym_parameters,
  },
  [4] = {
    [0] = alias_sym_parameters,
    [2] = alias_sym_body,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__lambda_content_repeat1, 3,
    aux_sym__lambda_content_repeat1,
    alias_sym_body,
    alias_sym_parameters,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 8,
  [11] = 11,
  [12] = 12,
  [13] = 8,
  [14] = 14,
  [15] = 15,
  [16] = 14,
  [17] = 17,
  [18] = 11,
  [19] = 19,
  [20] = 20,
  [21] = 19,
  [22] = 20,
  [23] = 17,
  [24] = 19,
  [25] = 20,
  [26] = 26,
  [27] = 14,
  [28] = 17,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 30,
  [33] = 30,
  [34] = 31,
  [35] = 31,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 48,
  [54] = 37,
  [55] = 42,
  [56] = 39,
  [57] = 40,
  [58] = 41,
  [59] = 36,
  [60] = 43,
  [61] = 38,
  [62] = 52,
  [63] = 46,
  [64] = 44,
  [65] = 45,
  [66] = 47,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 69,
  [71] = 68,
  [72] = 69,
  [73] = 68,
  [74] = 74,
  [75] = 75,
  [76] = 75,
  [77] = 77,
  [78] = 78,
  [79] = 75,
  [80] = 80,
  [81] = 36,
  [82] = 47,
  [83] = 83,
  [84] = 46,
  [85] = 38,
  [86] = 43,
  [87] = 37,
  [88] = 88,
  [89] = 42,
  [90] = 48,
  [91] = 39,
  [92] = 40,
  [93] = 41,
};

static const TSCharacterRange sym__symbol_shared_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '\''}, {'*', '9'}, {'<', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x27e7}, {0x27ea, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '"', 84,
        '(', 81,
        ')', 82,
        '.', 75,
        ':', 83,
        ';', 69,
        '[', 79,
        '\\', 31,
        ']', 80,
        '{', 77,
        '}', 78,
        '+', 71,
        '-', 71,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != 0x27e8 &&
          lookahead != 0x27e9) ADVANCE(74);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ';') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(84);
      if (lookahead == ';') ADVANCE(69);
      if (lookahead == '\\') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      if (lookahead != 0) ADVANCE(85);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == '.') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'a') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'c') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'd') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'g') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'g') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'i') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 18:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'k') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'l') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'p') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(13);
      if (lookahead == 's') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'r') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 25:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 't') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 27:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == 'v') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == '(') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == '(') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 30:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ADVANCE_MAP(
        '.', 76,
        '\\', 74,
        '0', 87,
        '<', 87,
        '>', 87,
        'a', 87,
        'b', 87,
        'n', 87,
        'r', 87,
        't', 87,
        '"', 74,
        '(', 74,
        ')', 74,
        ':', 74,
        ';', 74,
        '[', 74,
        ']', 74,
        's', 74,
        '{', 74,
        '}', 74,
        0x27e8, 74,
        0x27e9, 74,
      );
      END_STATE();
    case 32:
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ':' ||
          lookahead == ';' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == 's' ||
          lookahead == '{' ||
          lookahead == '}' ||
          lookahead == 0x27e8 ||
          lookahead == 0x27e9) ADVANCE(74);
      END_STATE();
    case 33:
      ADVANCE_MAP(
        '0', 87,
        '<', 87,
        '>', 87,
        '\\', 87,
        'a', 87,
        'b', 87,
        'n', 87,
        'r', 87,
        't', 87,
      );
      END_STATE();
    case 34:
      if (lookahead == '"' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ':' ||
          lookahead == ';' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == 's' ||
          lookahead == '{' ||
          lookahead == '}' ||
          lookahead == 0x27e8 ||
          lookahead == 0x27e9) ADVANCE(74);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '"', 84,
        '(', 81,
        ')', 82,
        '.', 75,
        ':', 83,
        ';', 69,
        '[', 79,
        '\\', 32,
        ']', 80,
        '{', 77,
        '}', 78,
        '+', 71,
        '-', 71,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != 0x27e8 &&
          lookahead != 0x27e9) ADVANCE(74);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == ' ') ADVANCE(64);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == ')') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == ' ') ADVANCE(47);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == ')') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == '.') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'a') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'a') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'a') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'a') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'a') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'd') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'e') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'g') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'g') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'i') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'k') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'l') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'n') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'r') ADVANCE(49);
      if (lookahead == 's') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'r') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'r') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 't') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'u') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == 'v') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ';') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_SEMI);
      if (lookahead == ';') ADVANCE(67);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__symbol_shared);
      if (lookahead == '\\') ADVANCE(34);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      if ((!eof && set_contains(sym__symbol_shared_character_set_1, 11, lookahead))) ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__symbol_shared);
      if (lookahead == '\\') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if ((!eof && set_contains(sym__symbol_shared_character_set_1, 11, lookahead))) ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__symbol_shared);
      if (lookahead == '\\') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if ((!eof && set_contains(sym__symbol_shared_character_set_1, 11, lookahead))) ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__symbol_shared);
      if (lookahead == '\\') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      if ((!eof && set_contains(sym__symbol_shared_character_set_1, 11, lookahead))) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__symbol_shared);
      if (lookahead == '\\') ADVANCE(34);
      if ((!eof && set_contains(sym__symbol_shared_character_set_1, 11, lookahead))) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '\\') ADVANCE(34);
      if ((!eof && set_contains(sym__symbol_shared_character_set_1, 11, lookahead))) ADVANCE(74);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BSLASH_DOT);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ';') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(85);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_string_escape);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'e') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 35},
  [3] = {.lex_state = 35},
  [4] = {.lex_state = 35},
  [5] = {.lex_state = 35},
  [6] = {.lex_state = 35},
  [7] = {.lex_state = 35},
  [8] = {.lex_state = 35},
  [9] = {.lex_state = 35},
  [10] = {.lex_state = 35},
  [11] = {.lex_state = 35},
  [12] = {.lex_state = 35},
  [13] = {.lex_state = 35},
  [14] = {.lex_state = 35},
  [15] = {.lex_state = 35},
  [16] = {.lex_state = 35},
  [17] = {.lex_state = 35},
  [18] = {.lex_state = 35},
  [19] = {.lex_state = 35},
  [20] = {.lex_state = 35},
  [21] = {.lex_state = 35},
  [22] = {.lex_state = 35},
  [23] = {.lex_state = 35},
  [24] = {.lex_state = 35},
  [25] = {.lex_state = 35},
  [26] = {.lex_state = 35},
  [27] = {.lex_state = 35},
  [28] = {.lex_state = 35},
  [29] = {.lex_state = 35},
  [30] = {.lex_state = 35},
  [31] = {.lex_state = 35},
  [32] = {.lex_state = 35},
  [33] = {.lex_state = 35},
  [34] = {.lex_state = 35},
  [35] = {.lex_state = 35},
  [36] = {.lex_state = 35},
  [37] = {.lex_state = 35},
  [38] = {.lex_state = 35},
  [39] = {.lex_state = 35},
  [40] = {.lex_state = 35},
  [41] = {.lex_state = 35},
  [42] = {.lex_state = 35},
  [43] = {.lex_state = 35},
  [44] = {.lex_state = 35},
  [45] = {.lex_state = 35},
  [46] = {.lex_state = 35},
  [47] = {.lex_state = 35},
  [48] = {.lex_state = 35},
  [49] = {.lex_state = 35},
  [50] = {.lex_state = 35},
  [51] = {.lex_state = 35},
  [52] = {.lex_state = 35},
  [53] = {.lex_state = 35},
  [54] = {.lex_state = 35},
  [55] = {.lex_state = 35},
  [56] = {.lex_state = 35},
  [57] = {.lex_state = 35},
  [58] = {.lex_state = 35},
  [59] = {.lex_state = 35},
  [60] = {.lex_state = 35},
  [61] = {.lex_state = 35},
  [62] = {.lex_state = 35},
  [63] = {.lex_state = 35},
  [64] = {.lex_state = 35},
  [65] = {.lex_state = 35},
  [66] = {.lex_state = 35},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {(TSStateId)(-1),},
  [82] = {(TSStateId)(-1),},
  [83] = {(TSStateId)(-1),},
  [84] = {(TSStateId)(-1),},
  [85] = {(TSStateId)(-1),},
  [86] = {(TSStateId)(-1),},
  [87] = {(TSStateId)(-1),},
  [88] = {(TSStateId)(-1),},
  [89] = {(TSStateId)(-1),},
  [90] = {(TSStateId)(-1),},
  [91] = {(TSStateId)(-1),},
  [92] = {(TSStateId)(-1),},
  [93] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_BSLASH_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_string_escape] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_long_string] = ACTIONS(1),
    [sym_long_string_escape] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(78),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_token1] = ACTIONS(7),
    [aux_sym_comment_token1] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_comment] = STATE(2),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym__lambda_content] = STATE(76),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(8),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(3)] = {
    [sym_comment] = STATE(3),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym__lambda_content] = STATE(75),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(13),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(4)] = {
    [sym_comment] = STATE(4),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym__lambda_content] = STATE(77),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(9),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(5)] = {
    [sym_comment] = STATE(5),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym__lambda_content] = STATE(80),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(12),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(6)] = {
    [sym_comment] = STATE(6),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym__lambda_content] = STATE(79),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(10),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(7)] = {
    [sym_comment] = STATE(7),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(7),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(39),
    [anon_sym_DOT] = ACTIONS(42),
    [anon_sym_BSLASH_DOT] = ACTIONS(44),
    [anon_sym_LBRACE] = ACTIONS(47),
    [anon_sym_RBRACE] = ACTIONS(50),
    [anon_sym_LBRACK] = ACTIONS(52),
    [anon_sym_LPAREN] = ACTIONS(55),
    [anon_sym_COLON] = ACTIONS(58),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [sym_number] = ACTIONS(64),
  },
  [STATE(8)] = {
    [sym_comment] = STATE(8),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(7),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(9)] = {
    [sym_comment] = STATE(9),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(7),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(10)] = {
    [sym_comment] = STATE(10),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(7),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(11)] = {
    [sym_comment] = STATE(11),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(75),
    [anon_sym_DOT] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(84),
    [anon_sym_LPAREN] = ACTIONS(86),
    [anon_sym_RPAREN] = ACTIONS(84),
    [anon_sym_COLON] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(92),
    [sym_number] = ACTIONS(95),
  },
  [STATE(12)] = {
    [sym_comment] = STATE(12),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(7),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(13)] = {
    [sym_comment] = STATE(13),
    [sym__form_shared] = STATE(50),
    [sym__form_not_dot] = STATE(51),
    [sym__symbol_not_dot] = STATE(50),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym__lambda_content_repeat1] = STATE(7),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(67),
    [anon_sym_BSLASH_DOT] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_RBRACE] = ACTIONS(100),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(14)] = {
    [sym_comment] = STATE(14),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(104),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(15)] = {
    [sym_comment] = STATE(15),
    [sym__form_shared] = STATE(65),
    [sym__form] = STATE(62),
    [sym_symbol] = STATE(65),
    [sym_lambda] = STATE(64),
    [sym_block] = STATE(64),
    [sym_data] = STATE(64),
    [sym_call] = STATE(64),
    [sym_pair] = STATE(64),
    [sym_string] = STATE(64),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(106),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(108),
    [anon_sym_DOT] = ACTIONS(108),
    [anon_sym_LBRACE] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(114),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_DQUOTE] = ACTIONS(118),
    [sym_number] = ACTIONS(120),
  },
  [STATE(16)] = {
    [sym_comment] = STATE(16),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(122),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(17)] = {
    [sym_comment] = STATE(17),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(124),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(18)] = {
    [sym_comment] = STATE(18),
    [sym__form_shared] = STATE(65),
    [sym__form] = STATE(62),
    [sym_symbol] = STATE(65),
    [sym_lambda] = STATE(64),
    [sym_block] = STATE(64),
    [sym_data] = STATE(64),
    [sym_call] = STATE(64),
    [sym_pair] = STATE(64),
    [sym_string] = STATE(64),
    [aux_sym_source_file_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(84),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(126),
    [anon_sym_DOT] = ACTIONS(126),
    [anon_sym_LBRACE] = ACTIONS(129),
    [anon_sym_LBRACK] = ACTIONS(132),
    [anon_sym_LPAREN] = ACTIONS(135),
    [anon_sym_COLON] = ACTIONS(138),
    [anon_sym_DQUOTE] = ACTIONS(141),
    [sym_number] = ACTIONS(144),
  },
  [STATE(19)] = {
    [sym_comment] = STATE(19),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(16),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(20)] = {
    [sym_comment] = STATE(20),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(17),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(149),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(21)] = {
    [sym_comment] = STATE(21),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(14),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(151),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(22)] = {
    [sym_comment] = STATE(22),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(23),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(153),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(23)] = {
    [sym_comment] = STATE(23),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(155),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(24)] = {
    [sym_comment] = STATE(24),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(27),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(157),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(25)] = {
    [sym_comment] = STATE(25),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(28),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(159),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(26)] = {
    [sym_comment] = STATE(26),
    [sym__form_shared] = STATE(65),
    [sym__form] = STATE(62),
    [sym_symbol] = STATE(65),
    [sym_lambda] = STATE(64),
    [sym_block] = STATE(64),
    [sym_data] = STATE(64),
    [sym_call] = STATE(64),
    [sym_pair] = STATE(64),
    [sym_string] = STATE(64),
    [aux_sym_source_file_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(161),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(108),
    [anon_sym_DOT] = ACTIONS(108),
    [anon_sym_LBRACE] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(114),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_DQUOTE] = ACTIONS(118),
    [sym_number] = ACTIONS(120),
  },
  [STATE(27)] = {
    [sym_comment] = STATE(27),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(163),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(28)] = {
    [sym_comment] = STATE(28),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(52),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_RPAREN] = ACTIONS(165),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(29)] = {
    [sym_comment] = STATE(29),
    [sym__form_shared] = STATE(83),
    [sym__form] = STATE(83),
    [sym_symbol] = STATE(83),
    [sym_lambda] = STATE(83),
    [sym_block] = STATE(83),
    [sym_data] = STATE(83),
    [sym_call] = STATE(83),
    [sym_pair] = STATE(83),
    [sym_string] = STATE(83),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(167),
    [anon_sym_DOT] = ACTIONS(167),
    [anon_sym_LBRACE] = ACTIONS(169),
    [anon_sym_LBRACK] = ACTIONS(171),
    [anon_sym_LPAREN] = ACTIONS(173),
    [anon_sym_COLON] = ACTIONS(175),
    [anon_sym_DQUOTE] = ACTIONS(177),
    [sym_number] = ACTIONS(179),
  },
  [STATE(30)] = {
    [sym_comment] = STATE(30),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(40),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(31)] = {
    [sym_comment] = STATE(31),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(33),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(32)] = {
    [sym_comment] = STATE(32),
    [sym__form_shared] = STATE(65),
    [sym__form] = STATE(57),
    [sym_symbol] = STATE(65),
    [sym_lambda] = STATE(64),
    [sym_block] = STATE(64),
    [sym_data] = STATE(64),
    [sym_call] = STATE(64),
    [sym_pair] = STATE(64),
    [sym_string] = STATE(64),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(108),
    [anon_sym_DOT] = ACTIONS(108),
    [anon_sym_LBRACE] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(112),
    [anon_sym_LPAREN] = ACTIONS(114),
    [anon_sym_COLON] = ACTIONS(116),
    [anon_sym_DQUOTE] = ACTIONS(118),
    [sym_number] = ACTIONS(120),
  },
  [STATE(33)] = {
    [sym_comment] = STATE(33),
    [sym__form_shared] = STATE(92),
    [sym__form] = STATE(92),
    [sym_symbol] = STATE(92),
    [sym_lambda] = STATE(92),
    [sym_block] = STATE(92),
    [sym_data] = STATE(92),
    [sym_call] = STATE(92),
    [sym_pair] = STATE(92),
    [sym_string] = STATE(92),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(167),
    [anon_sym_DOT] = ACTIONS(167),
    [anon_sym_LBRACE] = ACTIONS(169),
    [anon_sym_LBRACK] = ACTIONS(171),
    [anon_sym_LPAREN] = ACTIONS(173),
    [anon_sym_COLON] = ACTIONS(175),
    [anon_sym_DQUOTE] = ACTIONS(177),
    [sym_number] = ACTIONS(181),
  },
  [STATE(34)] = {
    [sym_comment] = STATE(34),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(32),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
  [STATE(35)] = {
    [sym_comment] = STATE(35),
    [sym__form_shared] = STATE(45),
    [sym__form] = STATE(30),
    [sym_symbol] = STATE(45),
    [sym_lambda] = STATE(44),
    [sym_block] = STATE(44),
    [sym_data] = STATE(44),
    [sym_call] = STATE(44),
    [sym_pair] = STATE(44),
    [sym_string] = STATE(44),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(5),
    [sym__symbol_shared] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(27),
    [sym_number] = ACTIONS(29),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(36), 1,
      sym_comment,
    ACTIONS(183), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(185), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [26] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(37), 1,
      sym_comment,
    ACTIONS(187), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(189), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [52] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(38), 1,
      sym_comment,
    ACTIONS(191), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(193), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [78] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(39), 1,
      sym_comment,
    ACTIONS(195), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(197), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [104] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(40), 1,
      sym_comment,
    ACTIONS(199), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(201), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [130] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(41), 1,
      sym_comment,
    ACTIONS(203), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(205), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [156] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(42), 1,
      sym_comment,
    ACTIONS(207), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(209), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [182] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(43), 1,
      sym_comment,
    ACTIONS(211), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(213), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [208] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(44), 1,
      sym_comment,
    ACTIONS(215), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(217), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [234] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym_comment,
    ACTIONS(219), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(221), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [260] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(46), 1,
      sym_comment,
    ACTIONS(223), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(225), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [286] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      sym_comment,
    ACTIONS(227), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(229), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [312] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(48), 1,
      sym_comment,
    ACTIONS(231), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(233), 10,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [338] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(49), 1,
      sym_comment,
    ACTIONS(235), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(237), 8,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [362] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(50), 1,
      sym_comment,
    ACTIONS(239), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(241), 8,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [386] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(51), 1,
      sym_comment,
    ACTIONS(243), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(245), 8,
      anon_sym_BSLASH_DOT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [410] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(52), 1,
      sym_comment,
    ACTIONS(247), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(249), 8,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [434] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(53), 1,
      sym_comment,
    ACTIONS(231), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(233), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [457] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(54), 1,
      sym_comment,
    ACTIONS(187), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(189), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [480] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(55), 1,
      sym_comment,
    ACTIONS(207), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(209), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [503] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(56), 1,
      sym_comment,
    ACTIONS(195), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(197), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [526] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(57), 1,
      sym_comment,
    ACTIONS(199), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(201), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [549] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(58), 1,
      sym_comment,
    ACTIONS(203), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(205), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [572] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(59), 1,
      sym_comment,
    ACTIONS(183), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(185), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [595] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(60), 1,
      sym_comment,
    ACTIONS(211), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(213), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [618] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(61), 1,
      sym_comment,
    ACTIONS(191), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(193), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [641] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(62), 1,
      sym_comment,
    ACTIONS(247), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(249), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [664] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(63), 1,
      sym_comment,
    ACTIONS(223), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(225), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [687] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(64), 1,
      sym_comment,
    ACTIONS(215), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(217), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [710] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(65), 1,
      sym_comment,
    ACTIONS(219), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(221), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [733] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    STATE(66), 1,
      sym_comment,
    ACTIONS(227), 2,
      sym__symbol_shared,
      anon_sym_DOT,
    ACTIONS(229), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_number,
  [756] = 5,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(251), 1,
      anon_sym_DQUOTE,
    ACTIONS(253), 2,
      aux_sym_string_token1,
      sym_string_escape,
    STATE(67), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [774] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(256), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      aux_sym_string_repeat1,
    STATE(68), 1,
      sym_comment,
    ACTIONS(258), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [794] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(260), 1,
      anon_sym_DQUOTE,
    STATE(69), 1,
      sym_comment,
    STATE(71), 1,
      aux_sym_string_repeat1,
    ACTIONS(258), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [814] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(262), 1,
      anon_sym_DQUOTE,
    STATE(70), 1,
      sym_comment,
    STATE(73), 1,
      aux_sym_string_repeat1,
    ACTIONS(258), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [834] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(264), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      aux_sym_string_repeat1,
    STATE(71), 1,
      sym_comment,
    ACTIONS(258), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [854] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(266), 1,
      anon_sym_DQUOTE,
    STATE(68), 1,
      aux_sym_string_repeat1,
    STATE(72), 1,
      sym_comment,
    ACTIONS(258), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [874] = 6,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    ACTIONS(268), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      aux_sym_string_repeat1,
    STATE(73), 1,
      sym_comment,
    ACTIONS(258), 2,
      aux_sym_string_token1,
      sym_string_escape,
  [894] = 4,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(9), 1,
      aux_sym_comment_token1,
    STATE(74), 1,
      sym_comment,
    ACTIONS(270), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      sym_string_escape,
  [909] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_comment,
  [922] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      sym_comment,
  [935] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    STATE(77), 1,
      sym_comment,
  [948] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(278), 1,
      ts_builtin_sym_end,
    STATE(78), 1,
      sym_comment,
  [961] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    STATE(79), 1,
      sym_comment,
  [974] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      anon_sym_SEMI,
    ACTIONS(282), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_comment,
  [987] = 1,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
  [991] = 1,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
  [995] = 1,
    ACTIONS(284), 1,
      ts_builtin_sym_end,
  [999] = 1,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
  [1003] = 1,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
  [1007] = 1,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
  [1011] = 1,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
  [1015] = 1,
    ACTIONS(286), 1,
      ts_builtin_sym_end,
  [1019] = 1,
    ACTIONS(209), 1,
      ts_builtin_sym_end,
  [1023] = 1,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
  [1027] = 1,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
  [1031] = 1,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
  [1035] = 1,
    ACTIONS(205), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(36)] = 0,
  [SMALL_STATE(37)] = 26,
  [SMALL_STATE(38)] = 52,
  [SMALL_STATE(39)] = 78,
  [SMALL_STATE(40)] = 104,
  [SMALL_STATE(41)] = 130,
  [SMALL_STATE(42)] = 156,
  [SMALL_STATE(43)] = 182,
  [SMALL_STATE(44)] = 208,
  [SMALL_STATE(45)] = 234,
  [SMALL_STATE(46)] = 260,
  [SMALL_STATE(47)] = 286,
  [SMALL_STATE(48)] = 312,
  [SMALL_STATE(49)] = 338,
  [SMALL_STATE(50)] = 362,
  [SMALL_STATE(51)] = 386,
  [SMALL_STATE(52)] = 410,
  [SMALL_STATE(53)] = 434,
  [SMALL_STATE(54)] = 457,
  [SMALL_STATE(55)] = 480,
  [SMALL_STATE(56)] = 503,
  [SMALL_STATE(57)] = 526,
  [SMALL_STATE(58)] = 549,
  [SMALL_STATE(59)] = 572,
  [SMALL_STATE(60)] = 595,
  [SMALL_STATE(61)] = 618,
  [SMALL_STATE(62)] = 641,
  [SMALL_STATE(63)] = 664,
  [SMALL_STATE(64)] = 687,
  [SMALL_STATE(65)] = 710,
  [SMALL_STATE(66)] = 733,
  [SMALL_STATE(67)] = 756,
  [SMALL_STATE(68)] = 774,
  [SMALL_STATE(69)] = 794,
  [SMALL_STATE(70)] = 814,
  [SMALL_STATE(71)] = 834,
  [SMALL_STATE(72)] = 854,
  [SMALL_STATE(73)] = 874,
  [SMALL_STATE(74)] = 894,
  [SMALL_STATE(75)] = 909,
  [SMALL_STATE(76)] = 922,
  [SMALL_STATE(77)] = 935,
  [SMALL_STATE(78)] = 948,
  [SMALL_STATE(79)] = 961,
  [SMALL_STATE(80)] = 974,
  [SMALL_STATE(81)] = 987,
  [SMALL_STATE(82)] = 991,
  [SMALL_STATE(83)] = 995,
  [SMALL_STATE(84)] = 999,
  [SMALL_STATE(85)] = 1003,
  [SMALL_STATE(86)] = 1007,
  [SMALL_STATE(87)] = 1011,
  [SMALL_STATE(88)] = 1015,
  [SMALL_STATE(89)] = 1019,
  [SMALL_STATE(90)] = 1023,
  [SMALL_STATE(91)] = 1027,
  [SMALL_STATE(92)] = 1031,
  [SMALL_STATE(93)] = 1035,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 2, 0, 3),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 3, 0, 4),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 2, 0, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__form_shared, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__form_shared, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__form, 1, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__form, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_data, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_data, 2, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__symbol_not_dot, 1, 0, 1),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__symbol_not_dot, 1, 0, 1),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__form_not_dot, 1, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__form_not_dot, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__lambda_content_repeat1, 1, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__lambda_content_repeat1, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [253] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 3, 0, 3),
  [278] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lambda_content, 2, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_long_string = 0,
  ts_external_token_long_string_escape = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_long_string] = sym_long_string,
  [ts_external_token_long_string_escape] = sym_long_string_escape,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_long_string] = true,
    [ts_external_token_long_string_escape] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_aardvark_external_scanner_create(void);
void tree_sitter_aardvark_external_scanner_destroy(void *);
bool tree_sitter_aardvark_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_aardvark_external_scanner_serialize(void *, char *);
void tree_sitter_aardvark_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_aardvark(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_aardvark_external_scanner_create,
      tree_sitter_aardvark_external_scanner_destroy,
      tree_sitter_aardvark_external_scanner_scan,
      tree_sitter_aardvark_external_scanner_serialize,
      tree_sitter_aardvark_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "aardvark",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
